[package]
name = "program-compiler-web-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
tar = "0.4.40"
thiserror = "1.0.56"
tokio = { version="1.36.0", features=["rt-multi-thread"]}
